export const CHANGE_CATEGORY = "playlist/CHANGE_CATEGORY";
export const CHANGE_CURRENT_CATEGORY = "playlist/CHANGE_CURRENT_CATEGORY";
export const CHANGE_CATEGORY_SONGS = "playlist/CHANGE_CATEGORY_SONGS";

export const PER_PAGE_NUMBER = 35;